import type { FastifyInstance } from "fastify";
import { buildWeightProgressExcel, buildWeightProgressPdf, type WeightProgressContext } from "../export/builders.js";
import type { AppPrisma } from "../../../infra/prisma.js";
import { composePreHandlers, requirePermission } from "../../identity/rbac/authorize.js";
import { dateOnlyParamSchema, entryListQuerySchema, exportQuerySchema, forecastQuerySchema, goalBodySchema, metricValueSchema } from "./schemas.js";
import { buildWeightForecastResponse, deleteWeightEntry, findAllWeightEntriesForExport, findWeightEntries, findWeightGoal, listWeightEntries, saveWeightGoal, upsertWeightEntryAndSyncProfile } from "./service.js";
import { serializeGoal, serializeMetricEntry, toDateOnly } from "./forecast.js";

export async function registerHealthWeightRoutes(app: FastifyInstance, prisma: AppPrisma): Promise<void> {
  app.get("/health/weight/entries", { preHandler: [app.authenticate, requirePermission("weights.read.self")] }, async (request) => listWeightEntries(prisma, request.user.id, entryListQuerySchema.parse(request.query)));
  app.put("/health/weight/entries/:date", { preHandler: [app.authenticate, requirePermission("weights.update.self")] }, async (request) => { const params = dateOnlyParamSchema.parse(request.params); const body = metricValueSchema.parse(request.body); return serializeMetricEntry(await upsertWeightEntryAndSyncProfile(prisma, request.user.id, toDateOnly(params.date), body.value)); });
  app.delete("/health/weight/entries/:date", { preHandler: [app.authenticate, requirePermission("weights.delete.self")] }, async (request, reply) => { const params = dateOnlyParamSchema.parse(request.params); await deleteWeightEntry(prisma, request.user.id, toDateOnly(params.date)); reply.status(204).send(); });
  app.get("/health/weight/goal", { preHandler: [app.authenticate, requirePermission("weights.read.self")] }, async (request) => { const goal = await findWeightGoal(prisma, request.user.id); return goal ? serializeGoal(goal) : null; });
  app.put("/health/weight/goal", { preHandler: [app.authenticate, requirePermission("weights.update.self")] }, async (request) => serializeGoal(await saveWeightGoal(prisma, request.user.id, goalBodySchema.parse(request.body))));
  app.get("/health/weight/forecast", { preHandler: [app.authenticate, requirePermission("weights.read.self")] }, async (request) => { const { range } = forecastQuerySchema.parse(request.query); const [goal, entries] = await Promise.all([findWeightGoal(prisma, request.user.id), findWeightEntries(prisma, request.user.id, range)]); return buildWeightForecastResponse(range, goal, entries); });
  app.get("/health/weight/dashboard", { preHandler: [app.authenticate, requirePermission("dashboard.read.self")] }, async (request) => { const { range } = forecastQuerySchema.parse(request.query); const [goal, entries] = await Promise.all([findWeightGoal(prisma, request.user.id), findWeightEntries(prisma, request.user.id, range)]); return { range, dataType: "weight", forecast: buildWeightForecastResponse(range, goal, entries) }; });
  app.get("/health/weight/export", { preHandler: composePreHandlers(app.authenticate, requirePermission("export.read.self"), requirePermission("weights.read.self")) }, async (request, reply) => { const { type } = exportQuerySchema.parse(request.query); const [goal, entries] = await Promise.all([findWeightGoal(prisma, request.user.id), findAllWeightEntriesForExport(prisma, request.user.id)]); const ctx: WeightProgressContext = { patientName: request.user.name ?? request.user.email, patientEmail: request.user.email, exportedAt: new Date() }; if (type === "excel") { const buffer = await buildWeightProgressExcel(entries, goal, ctx); reply.header("content-type", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet").header("content-disposition", "attachment; filename=\"weight-progress-report.xlsx\""); return buffer; } const buffer = await buildWeightProgressPdf(entries, goal, ctx); reply.header("content-type", "application/pdf").header("content-disposition", "attachment; filename=\"weight-progress-report.pdf\""); return buffer; });
}
